### ISSUE TITLE
[Request] Item to get out

### ISSUE THREAD

**Issue by GWSheridan** [MoreThanHidden/RestrictedPortals#15]
Any chance could add config option to get out of the nether

**Comment by MoreThanHidden** [comment]
Sorry, I'm not to sure I know what you mean, you wan't start in the nether and craft an item to get out? or you got stuck in the nether after adding the mod?

**Comment by GWSheridan** [comment]
Making a pack an wanted to restrict the portal been used to get out the nether till late game. As the pack is based on nether survival. Been looking for a mod the would be able to do that. Thought I would ask if this could be added to this mod please

**Comment by GWSheridan** [comment]
Would this be possible

**Comment by MoreThanHidden** [comment]
hmm probably is already possible with configs haven't tested yet

**Comment by MokahTGS** [comment]
This does not work by simply using the configs.  If you try to add the overworld to the configs you get a crash.

https://pastebin.com/ZPiMNGJw

I would very much like you to add a way to restrict going to the overworld through either the nether portal or the end portal.

**Comment by MoreThanHidden** [comment]
Same as #24 Works for me, with example config:
![image](https://user-images.githubusercontent.com/1351964/90329453-96409900-dfd7-11ea-9c37-d40b42d5aa10.png)

![image](https://user-images.githubusercontent.com/1351964/90329479-d3a52680-dfd7-11ea-87cd-27543593ef8f.png)

```toml
[options]
	#Message that displays when Teleport is blocked
	blockedmessage = "Please obtain a %item% to enter the %dim%"
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end,minecraft:overworld"
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "minecraft:flint_and_steel,minecraft:ender_eye,minecraft:grass_block"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,End,Overworld"

```
