### ISSUE TITLE
Can still go through portal when in nether

### ISSUE THREAD

**Issue by MineCrak** [MoreThanHidden/RestrictedPortals#24]
Minecraft 1.12.2
Forge 2847
RestrictedPortals 1.12-0.6.3

Perfect Spawn 1.12.2-2.1
SleepingOverhaul 1.12.2-1.0.0

Hello, your mod is almost perfect for what I need for my specialty world and modpack. 

The only problem I've found is that even when the cfg is set so that I can't use portals, haven't made a certain recipe, I can still enter and use a portal from within the nether to the overworld. 

For my setup this will be a problem as I'm completely shutting down all portal travel and making them get to the Nether and End via other methods. But once they are in the Nether they will be able to break the theme by getting back to the overworld via portals which destroys the entire structure of the world. 

Fortunately the End seems to be ok. Your mod successfully stops the central portal from working there. 

I have tested this setup with both Cubic Chunks and without it but have the exact same results. My need is to use it with Cubic Chunks so I will be needing to use mc 1.12.2 for a while. I know you are working on versions for newer mc versions but please consider releasing a fixed version of 1.12.2, it will be used to very good effect. 

* btw: I'm using Perfect Spawn to enable being able to set respawn in other dims. The only reason I'm currently using SleepingOverhaul too is because even though the Perfect Spawn spawn relocation works the beds are still exploding in the Nether even though they aren't supposed to, and Sleeping overhaul does successfully stop the explosions but it won't change spawn location (by design). Together they make both needs work, lol.

**Comment by MoreThanHidden** [comment]
Works for me, with example config:
![image](https://user-images.githubusercontent.com/1351964/90329453-96409900-dfd7-11ea-9c37-d40b42d5aa10.png)

![image](https://user-images.githubusercontent.com/1351964/90329479-d3a52680-dfd7-11ea-87cd-27543593ef8f.png)

```toml
[options]
	#Message that displays when Teleport is blocked
	blockedmessage = "Please obtain a %item% to enter the %dim%"
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end,minecraft:overworld"
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "minecraft:flint_and_steel,minecraft:ender_eye,minecraft:grass_block"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,End,Overworld"

```
